/**
 * Публичные schema names для Modeler DSL.
 */
export const Modeler = {
  Root: 'Modeler.Root',
  Background: 'Modeler.Background',
  Grid: 'Modeler.Grid',
  BpmnRecipeLayerView: 'Modeler.BpmnRecipeLayerView',
  BasicRectView: 'Modeler.BasicRectView',
  BpmnAssociationView: 'Modeler.BpmnAssociationView',
  BpmnMessageFlowView: 'Modeler.BpmnMessageFlowView',
  BpmnFlowView: 'Modeler.BpmnFlowView',
  BpmnEventView: 'Modeler.BpmnEventView',
  BpmnTaskView: 'Modeler.BpmnTaskView',
  BpmnActivityView: 'Modeler.BpmnActivityView',
  BpmnGatewayView: 'Modeler.BpmnGatewayView',
  BpmnTextAnnotationView: 'Modeler.BpmnTextAnnotationView',
  BpmnGroupView: 'Modeler.BpmnGroupView',
  BpmnDataObjectView: 'Modeler.BpmnDataObjectView',
  BpmnDataStoreView: 'Modeler.BpmnDataStoreView',
  BpmnParticipantView: 'Modeler.BpmnParticipantView',
  PortView: 'Modeler.PortView',
  EdgeWaypointHandleView: 'Modeler.EdgeWaypointHandleView',
  ResizeHandleView: 'Modeler.ResizeHandleView',
  RotateHandleView: 'Modeler.RotateHandleView',
  MiniMap: 'Modeler.MiniMap',
  MarqueeSelection: 'Modeler.MarqueeSelection',
  ContextPad: 'Modeler.ContextPad',
  ElementColorMenu: 'Modeler.ElementColorMenu',
  ElementVariantMenu: 'Modeler.ElementVariantMenu',
  BrandLogo: 'Modeler.BrandLogo',
  Palette: 'Modeler.Palette',
  DownloadControls: 'Modeler.DownloadControls',
  BpmnValidationBadge: 'Modeler.BpmnValidationBadge',
  BpmnValidationDialog: 'Modeler.BpmnValidationDialog',
  ZoomControls: 'Modeler.ZoomControls',
  SettingsDialog: 'Modeler.SettingsDialog',
  SettingsButton: 'Modeler.SettingsButton',
  SettingsCategory: 'Modeler.SettingsCategory',
  SettingsSection: 'Modeler.SettingsSection',
} as const
